Update for hooks fail.

diff --git a/build/coder/hooks/pre_build b/build/coder/hooks/pre_build
--- a/build/coder/hooks/pre_build
+++ b/build/coder/hooks/pre_build
@@ -4,18 +4,25 @@ coderlist=$(curl -s https://api.github.com/repos/codercom/code-server/tags | gre
 coderpath=$(echo $coderlist | cut -d '"' -f 4) || true
 coderver=$(echo $coderpath | cut -d '/' -f 8)
 
-id=$(docker create ${DOCKER_REPO:16}:code-server) || true
-docker cp ${id}:/etc/CODER_VER out.txt
-docker rm -v $id || true
-build_ver="$(<out.txt)" || true
-
-echo "coder lastet version: ${coderver}, builded version: ${build_ver}"
-
-if [[ ${coderver} == ${build_ver} ]]; then
-	echo "=> No need build"
+if [[ -z "${coderver}" ]]; then
+	echo "=> Can't get coder version."
+	echo "${coderver}"
+	echo "${coderpath}"
+	echo "${coderlist}"
 else
-	echo "=> Building the coder-stretch-slim"
-	docker build --build-arg CODER_VERSION=$coderver -t $DOCKER_REPO:coder-stretch-slim -t $DOCKER_REPO:coder-stretch-slim$coderver - < ${PWD}/coder-gen/Dockerfile
-	docker push $DOCKER_REPO:coder-stretch-slim
-	docker push $DOCKER_REPO:coder-stretch-slim$coderver
+	id=$(docker create ${DOCKER_REPO:16}:code-server) || true
+	docker cp ${id}:/etc/CODER_VER out.txt
+	docker rm -v $id || true
+	build_ver="$(<out.txt)" || true
+
+	echo "coder lastet version: ${coderver}, builded version: ${build_ver}"
+
+	if [[ ${coderver} == ${build_ver} ]]; then
+		echo "=> No need build"
+	else
+		echo "=> Building the coder-stretch-slim"
+		docker build --build-arg CODER_VERSION=$coderver -t $DOCKER_REPO:coder-stretch-slim -t $DOCKER_REPO:coder-stretch-slim$coderver - < ${PWD}/coder-gen/Dockerfile
+		docker push $DOCKER_REPO:coder-stretch-slim
+		docker push $DOCKER_REPO:coder-stretch-slim$coderver
+	fi
 fi
